package examen1p2_andresnuila;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author enuil
 */
public class Pantalla_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla_Principal
     */
    public Pantalla_Principal() {
        initComponents();
        if (cb_TipoDeUsuario.getSelectedIndex() == 0) {
            tf_NewCargoGerente.setEnabled(true);
            tf_NewUserGerente.setEnabled(true);
            tf_gerentePassword.setEnabled(true);
            tf_newOcupacionPersonal.setEnabled(false);
            tf_newTrabajadoPersonal.setEnabled(false);
            tf_newHorarioPersonal.setEnabled(false);
            tf_Sueldo.setEnabled(false);
        } else if (cb_TipoDeUsuario.getSelectedIndex() == 1) {
            tf_NewCargoGerente.setEnabled(false);
            tf_NewUserGerente.setEnabled(false);
            tf_gerentePassword.setEnabled(false);
            tf_newOcupacionPersonal.setEnabled(true);
            tf_newTrabajadoPersonal.setEnabled(true);
            tf_newHorarioPersonal.setEnabled(true);
            tf_Sueldo.setEnabled(true);
        }
        if (cb_ListaTiposObjetos.getSelectedIndex() == 0) {
            tf_talla.setEnabled(true);
            ta_NewSuela.setEnabled(true);
            tf_NewComodida.setEnabled(true);
            rb_L.setEnabled(false);
            rb_M.setEnabled(false);
            rb_S.setEnabled(false);
            tf_Newtela.setEnabled(false);
            tf_NewPais.setEnabled(false);
            ta_newdHogar.setEnabled(false);
            ta_NewInstrucciones.setEnabled(false);
            tf_newGarantia3.setEnabled(false);
        } else if (cb_ListaTiposObjetos.getSelectedIndex() == 1) {
            tf_talla.setEnabled(false);
            ta_NewSuela.setEnabled(false);
            tf_NewComodida.setEnabled(false);
            rb_L.setEnabled(true);
            rb_M.setEnabled(true);
            rb_S.setEnabled(true);
            tf_Newtela.setEnabled(true);
            tf_NewPais.setEnabled(true);
            ta_newdHogar.setEnabled(false);
            ta_NewInstrucciones.setEnabled(false);
            tf_newGarantia3.setEnabled(false);
        } else if (cb_ListaTiposObjetos.getSelectedIndex() == 2) {
            tf_talla.setEnabled(false);
            ta_NewSuela.setEnabled(false);
            tf_NewComodida.setEnabled(false);
            rb_L.setEnabled(false);
            rb_M.setEnabled(false);
            rb_S.setEnabled(false);
            tf_Newtela.setEnabled(false);
            tf_NewPais.setEnabled(false);
            ta_newdHogar.setEnabled(true);
            ta_NewInstrucciones.setEnabled(true);
            tf_newGarantia3.setEnabled(true);
        }
        setLocationRelativeTo(null);
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_TipoDeUsuario.getModel();
        modelo.addElement("Gerente");
        modelo.addElement("Personal General");
        DefaultComboBoxModel modeloO = (DefaultComboBoxModel) cb_ListaTiposObjetos.getModel();
        modeloO.addElement("Zapato");
        modeloO.addElement("Ropa");
        modeloO.addElement("Hogar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Crear = new javax.swing.JDialog();
        jb_CrearPersona = new javax.swing.JButton();
        jb_CrearObjeto = new javax.swing.JButton();
        CreacionPersonal = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cb_TipoDeUsuario = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_NewId = new javax.swing.JTextField();
        tf_newName = new javax.swing.JTextField();
        tf_NewEdad = new javax.swing.JTextField();
        rb_NewM = new javax.swing.JRadioButton();
        rb_NewF = new javax.swing.JRadioButton();
        rb_NewSoltero = new javax.swing.JRadioButton();
        rb_NewCasado = new javax.swing.JRadioButton();
        tf_NewAltura = new javax.swing.JTextField();
        tf_newPeso = new javax.swing.JTextField();
        tf_NewUserGerente = new javax.swing.JTextField();
        tf_NewCargoGerente = new javax.swing.JTextField();
        tf_newOcupacionPersonal = new javax.swing.JTextField();
        tf_newHorarioPersonal = new javax.swing.JTextField();
        tf_newTrabajadoPersonal = new javax.swing.JTextField();
        jb_crear = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        tf_gerentePassword = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        tf_Sueldo = new javax.swing.JTextField();
        jb_regresar = new javax.swing.JButton();
        grupoSexo = new javax.swing.ButtonGroup();
        grupoEstadoCivil = new javax.swing.ButtonGroup();
        Listar = new javax.swing.JDialog();
        jb_listarPersonas = new javax.swing.JButton();
        jb_listarObjetos = new javax.swing.JButton();
        ListarPersonas = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_ListaPersonal = new javax.swing.JTable();
        jb_EliminarPersona = new javax.swing.JButton();
        jb_Regresar2 = new javax.swing.JButton();
        CrearObjetos = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cb_ListaTiposObjetos = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jb_Color = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        tf_Newmarca = new javax.swing.JTextField();
        tf_NewTamaño = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_NewCalidad = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_NewInstrucciones = new javax.swing.JTextArea();
        tf_talla = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_NewSuela = new javax.swing.JTextArea();
        tf_NewComodida = new javax.swing.JTextField();
        tf_Newtela = new javax.swing.JTextField();
        tf_NewPais = new javax.swing.JTextField();
        rb_S = new javax.swing.JRadioButton();
        rb_M = new javax.swing.JRadioButton();
        rb_L = new javax.swing.JRadioButton();
        tf_newGarantia3 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_newdHogar = new javax.swing.JTextArea();
        cb_personas = new javax.swing.JComboBox<>();
        jb_crearObjeto = new javax.swing.JButton();
        jb_regresar3 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        ta_newDescripcion = new javax.swing.JTextArea();
        grputoTallas = new javax.swing.ButtonGroup();
        ListarObjetos = new javax.swing.JDialog();
        jScrollPane7 = new javax.swing.JScrollPane();
        jt_InventarioObjetos = new javax.swing.JTable();
        jb_eliminar2 = new javax.swing.JButton();
        jb_regresar4 = new javax.swing.JButton();
        Eliminar = new javax.swing.JDialog();
        jb_ElPersona = new javax.swing.JButton();
        jb_ElObjeto = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        Eliminar_Personal = new javax.swing.JDialog();
        jb_EliminarTotal3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tablaBorra = new javax.swing.JComboBox<>();
        Borrar_Objetos = new javax.swing.JDialog();
        TablaBorrar_Objetos = new javax.swing.JComboBox<>();
        jb_elTotalObj = new javax.swing.JButton();
        jb_regresarElOvj = new javax.swing.JButton();
        jb_Crear = new javax.swing.JButton();
        jb_Modificar = new javax.swing.JButton();
        jb_Eliminar = new javax.swing.JButton();
        jb_Listar = new javax.swing.JButton();

        jb_CrearPersona.setText("Persona");
        jb_CrearPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CrearPersonaMouseClicked(evt);
            }
        });

        jb_CrearObjeto.setText("Objeto");
        jb_CrearObjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CrearObjetoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CrearLayout = new javax.swing.GroupLayout(Crear.getContentPane());
        Crear.getContentPane().setLayout(CrearLayout);
        CrearLayout.setHorizontalGroup(
            CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jb_CrearPersona)
                .addGap(142, 142, 142)
                .addComponent(jb_CrearObjeto)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        CrearLayout.setVerticalGroup(
            CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addGroup(CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_CrearPersona)
                    .addComponent(jb_CrearObjeto))
                .addContainerGap(242, Short.MAX_VALUE))
        );

        jLabel1.setText("ID");

        jLabel2.setText("Nombre");

        jLabel3.setText("Edad");

        jLabel4.setText("Sexo");

        jLabel5.setText("Estado Civil");

        jLabel6.setText("Altura");

        jLabel7.setText("Peso");

        cb_TipoDeUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_TipoDeUsuarioItemStateChanged(evt);
            }
        });

        jLabel8.setText("Tipo de Usuario");

        jLabel9.setText("Username(Gerente)");

        jLabel10.setText("Cargo(Gerente)");

        jLabel11.setText("Ocupacion(Personal)");

        jLabel12.setText("Horario");

        jLabel13.setText("Tiempo de trabajar (En semanas)");

        tf_NewId.setText("jTextField1");

        tf_newName.setText("jTextField2");

        tf_NewEdad.setText("jTextField3");

        grupoSexo.add(rb_NewM);
        rb_NewM.setText("M");
        rb_NewM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_NewMActionPerformed(evt);
            }
        });

        grupoSexo.add(rb_NewF);
        rb_NewF.setText("F");

        grupoEstadoCivil.add(rb_NewSoltero);
        rb_NewSoltero.setText("Soltero");

        grupoEstadoCivil.add(rb_NewCasado);
        rb_NewCasado.setText("Casado");

        tf_NewAltura.setText("jTextField1");

        tf_newPeso.setText("jTextField1");

        tf_NewUserGerente.setText("jTextField1");

        tf_NewCargoGerente.setText("jTextField1");

        tf_newOcupacionPersonal.setText("jTextField1");

        tf_newHorarioPersonal.setText("jTextField1");

        tf_newTrabajadoPersonal.setText("jTextField1");

        jb_crear.setText("Crear");
        jb_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearMouseClicked(evt);
            }
        });

        jLabel14.setText("Password");

        tf_gerentePassword.setText("jPasswordField1");

        jLabel15.setText("Sueldo");

        tf_Sueldo.setText("jTextField1");

        jb_regresar.setText("REGRESAR");
        jb_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_regresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CreacionPersonalLayout = new javax.swing.GroupLayout(CreacionPersonal.getContentPane());
        CreacionPersonal.getContentPane().setLayout(CreacionPersonalLayout);
        CreacionPersonalLayout.setHorizontalGroup(
            CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreacionPersonalLayout.createSequentialGroup()
                .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreacionPersonalLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jb_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_regresar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreacionPersonalLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CreacionPersonalLayout.createSequentialGroup()
                                .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(40, 40, 40)
                                .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_NewM)
                                    .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_NewId, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                        .addComponent(tf_newName)
                                        .addComponent(tf_NewEdad))))
                            .addGroup(CreacionPersonalLayout.createSequentialGroup()
                                .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(CreacionPersonalLayout.createSequentialGroup()
                                        .addComponent(rb_NewSoltero)
                                        .addGap(18, 18, 18)
                                        .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rb_NewF)
                                            .addComponent(rb_NewCasado)))
                                    .addComponent(tf_NewAltura)
                                    .addComponent(tf_newPeso))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(CreacionPersonalLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_Sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CreacionPersonalLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_newTrabajadoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)
                            .addGroup(CreacionPersonalLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(cb_TipoDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CreacionPersonalLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_newHorarioPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CreacionPersonalLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_newOcupacionPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CreacionPersonalLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_gerentePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_NewUserGerente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreacionPersonalLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_NewCargoGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        CreacionPersonalLayout.setVerticalGroup(
            CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreacionPersonalLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(tf_NewId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_TipoDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreacionPersonalLayout.createSequentialGroup()
                        .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_NewUserGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_NewCargoGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(13, 13, 13))
                    .addGroup(CreacionPersonalLayout.createSequentialGroup()
                        .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_newName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_NewEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreacionPersonalLayout.createSequentialGroup()
                        .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(rb_NewM)
                            .addComponent(rb_NewF)
                            .addComponent(jLabel14))
                        .addGap(22, 22, 22)
                        .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(rb_NewSoltero)
                            .addComponent(rb_NewCasado)
                            .addComponent(jLabel11)
                            .addComponent(tf_newOcupacionPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tf_gerentePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(tf_NewAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12)
                    .addComponent(tf_newHorarioPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_newPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tf_newTrabajadoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_Sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreacionPersonalLayout.createSequentialGroup()
                        .addComponent(jb_crear)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreacionPersonalLayout.createSequentialGroup()
                        .addComponent(jb_regresar)
                        .addContainerGap())))
        );

        jb_listarPersonas.setText("Personas");
        jb_listarPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_listarPersonasMouseClicked(evt);
            }
        });

        jb_listarObjetos.setText("Objetos");
        jb_listarObjetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_listarObjetosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ListarLayout = new javax.swing.GroupLayout(Listar.getContentPane());
        Listar.getContentPane().setLayout(ListarLayout);
        ListarLayout.setHorizontalGroup(
            ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jb_listarPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(jb_listarObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        ListarLayout.setVerticalGroup(
            ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_listarObjetos, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(jb_listarPersonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(243, Short.MAX_VALUE))
        );

        jt_ListaPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Rol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_ListaPersonal);

        jb_EliminarPersona.setText("Eliminar");
        jb_EliminarPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_EliminarPersonaMouseClicked(evt);
            }
        });

        jb_Regresar2.setText("Regresar");
        jb_Regresar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_Regresar2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ListarPersonasLayout = new javax.swing.GroupLayout(ListarPersonas.getContentPane());
        ListarPersonas.getContentPane().setLayout(ListarPersonasLayout);
        ListarPersonasLayout.setHorizontalGroup(
            ListarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarPersonasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addGroup(ListarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_EliminarPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_Regresar2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        ListarPersonasLayout.setVerticalGroup(
            ListarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarPersonasLayout.createSequentialGroup()
                .addGroup(ListarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListarPersonasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ListarPersonasLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jb_EliminarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(jb_Regresar2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel16.setText("Color");

        jLabel17.setText("Marca");

        jLabel18.setText("Descripcion");

        jLabel19.setText("Tamaño");

        jLabel20.setText("Calidad");

        jLabel21.setText("Que persona lo ingreso al sistema");

        jLabel22.setText("Tipo de objeto");

        cb_ListaTiposObjetos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_ListaTiposObjetosItemStateChanged(evt);
            }
        });

        jLabel23.setText("Talla");

        jLabel24.setText("Descripcion Suela");

        jLabel25.setText("Escala de comodidad");

        jLabel26.setText("Talla");

        jLabel27.setText("Tipo de Tela");

        jLabel28.setText("Pais de elaboracion");

        jLabel29.setText("Descripcion");

        jLabel31.setText("Instruciones");

        jLabel32.setText("Tiempo de garantia en meses");

        jb_Color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ColorMouseClicked(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel33.setText("Presione para selecionar un color");

        tf_Newmarca.setText("jTextField1");

        tf_NewTamaño.setText("jTextField1");

        ta_NewCalidad.setColumns(20);
        ta_NewCalidad.setRows(5);
        jScrollPane2.setViewportView(ta_NewCalidad);

        ta_NewInstrucciones.setColumns(20);
        ta_NewInstrucciones.setRows(5);
        jScrollPane3.setViewportView(ta_NewInstrucciones);

        tf_talla.setText("jTextField1");

        ta_NewSuela.setColumns(20);
        ta_NewSuela.setRows(5);
        jScrollPane4.setViewportView(ta_NewSuela);

        tf_NewComodida.setText("jTextField2");

        tf_Newtela.setText("jTextField4");

        tf_NewPais.setText("jTextField5");

        grputoTallas.add(rb_S);
        rb_S.setText("s");

        grputoTallas.add(rb_M);
        rb_M.setText("m");

        grputoTallas.add(rb_L);
        rb_L.setText("l");

        tf_newGarantia3.setText("jTextField3");

        ta_newdHogar.setColumns(20);
        ta_newdHogar.setRows(5);
        jScrollPane5.setViewportView(ta_newdHogar);

        jb_crearObjeto.setText("CREAR");
        jb_crearObjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearObjetoMouseClicked(evt);
            }
        });

        jb_regresar3.setText("REGRESAR");
        jb_regresar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_regresar3MouseClicked(evt);
            }
        });

        ta_newDescripcion.setColumns(20);
        ta_newDescripcion.setRows(5);
        jScrollPane6.setViewportView(ta_newDescripcion);

        javax.swing.GroupLayout CrearObjetosLayout = new javax.swing.GroupLayout(CrearObjetos.getContentPane());
        CrearObjetos.getContentPane().setLayout(CrearObjetosLayout);
        CrearObjetosLayout.setHorizontalGroup(
            CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearObjetosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearObjetosLayout.createSequentialGroup()
                        .addComponent(cb_personas, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(CrearObjetosLayout.createSequentialGroup()
                        .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(CrearObjetosLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CrearObjetosLayout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel33)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel30))
                                    .addGroup(CrearObjetosLayout.createSequentialGroup()
                                        .addGap(125, 125, 125)
                                        .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tf_Newmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jb_Color, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_NewTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel20)
                            .addGroup(CrearObjetosLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearObjetosLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tf_talla, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_ListaTiposObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32))
                            .addGroup(CrearObjetosLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CrearObjetosLayout.createSequentialGroup()
                                        .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(CrearObjetosLayout.createSequentialGroup()
                                                .addComponent(jLabel29)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(CrearObjetosLayout.createSequentialGroup()
                                                .addComponent(jLabel28)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tf_NewPais, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(CrearObjetosLayout.createSequentialGroup()
                                                .addComponent(jLabel27)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tf_Newtela, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap())
                                    .addGroup(CrearObjetosLayout.createSequentialGroup()
                                        .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(CrearObjetosLayout.createSequentialGroup()
                                                    .addComponent(jLabel32)
                                                    .addGap(28, 28, 28)
                                                    .addComponent(tf_newGarantia3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(CrearObjetosLayout.createSequentialGroup()
                                                    .addComponent(jLabel24)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jb_crearObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel23)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearObjetosLayout.createSequentialGroup()
                                                    .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel25)
                                                        .addComponent(jLabel26))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(CrearObjetosLayout.createSequentialGroup()
                                                            .addComponent(rb_S)
                                                            .addGap(31, 31, 31)
                                                            .addComponent(rb_M)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(rb_L))
                                                        .addComponent(tf_NewComodida, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(CrearObjetosLayout.createSequentialGroup()
                                                    .addComponent(jLabel31)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jb_regresar3, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 12, Short.MAX_VALUE))))))))
        );
        CrearObjetosLayout.setVerticalGroup(
            CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearObjetosLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cb_ListaTiposObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addGroup(CrearObjetosLayout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CrearObjetosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jb_Color, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CrearObjetosLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tf_talla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23))))))
                .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearObjetosLayout.createSequentialGroup()
                        .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CrearObjetosLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(tf_Newmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(CrearObjetosLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel24)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearObjetosLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(4, 4, 4)
                                .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_NewComodida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(tf_NewTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(rb_S)
                            .addComponent(rb_M)
                            .addComponent(rb_L)))
                    .addGroup(CrearObjetosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearObjetosLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(tf_Newtela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CrearObjetosLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CrearObjetosLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_NewPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28))
                                .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CrearObjetosLayout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addComponent(jLabel29))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearObjetosLayout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(CrearObjetosLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearObjetosLayout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearObjetosLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(tf_newGarantia3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(30, 30, 30)
                .addComponent(cb_personas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_crearObjeto)
                .addGap(18, 18, 18)
                .addComponent(jb_regresar3)
                .addContainerGap())
        );

        jt_InventarioObjetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Tamaño", "Calidad", "Descripcion", "Entrega", "Color"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jt_InventarioObjetos);

        jb_eliminar2.setText("ELIMINAR");
        jb_eliminar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_eliminar2MouseClicked(evt);
            }
        });

        jb_regresar4.setText("REGRESAR");
        jb_regresar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_regresar4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ListarObjetosLayout = new javax.swing.GroupLayout(ListarObjetos.getContentPane());
        ListarObjetos.getContentPane().setLayout(ListarObjetosLayout);
        ListarObjetosLayout.setHorizontalGroup(
            ListarObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarObjetosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addGroup(ListarObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_eliminar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_regresar4, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        ListarObjetosLayout.setVerticalGroup(
            ListarObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarObjetosLayout.createSequentialGroup()
                .addGroup(ListarObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListarObjetosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ListarObjetosLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jb_eliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(jb_regresar4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jb_ElPersona.setText("Eliminar Persona");
        jb_ElPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ElPersonaMouseClicked(evt);
            }
        });

        jb_ElObjeto.setText("Eliminar Objeto");
        jb_ElObjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ElObjetoMouseClicked(evt);
            }
        });

        jLabel34.setText("VENTANA PARA ELIMINAR TOTALMENTE DEL SISTEMA");

        javax.swing.GroupLayout EliminarLayout = new javax.swing.GroupLayout(Eliminar.getContentPane());
        Eliminar.getContentPane().setLayout(EliminarLayout);
        EliminarLayout.setHorizontalGroup(
            EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jb_ElPersona)
                .addGap(115, 115, 115)
                .addComponent(jb_ElObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EliminarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel34)
                .addGap(170, 170, 170))
        );
        EliminarLayout.setVerticalGroup(
            EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addGroup(EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_ElObjeto, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(jb_ElPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        jb_EliminarTotal3.setText("ELIMINAR TOTALMENTE");
        jb_EliminarTotal3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_EliminarTotal3MouseClicked(evt);
            }
        });

        jButton2.setText("REGRESAR");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Eliminar_PersonalLayout = new javax.swing.GroupLayout(Eliminar_Personal.getContentPane());
        Eliminar_Personal.getContentPane().setLayout(Eliminar_PersonalLayout);
        Eliminar_PersonalLayout.setHorizontalGroup(
            Eliminar_PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Eliminar_PersonalLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jb_EliminarTotal3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Eliminar_PersonalLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(tablaBorra, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        Eliminar_PersonalLayout.setVerticalGroup(
            Eliminar_PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Eliminar_PersonalLayout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(tablaBorra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addGroup(Eliminar_PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(jb_EliminarTotal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(142, 142, 142))
        );

        jb_elTotalObj.setText("ELIMINAR TOTALMENTE");
        jb_elTotalObj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_elTotalObjMouseClicked(evt);
            }
        });

        jb_regresarElOvj.setText("REGRESAR");
        jb_regresarElOvj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_regresarElOvjMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Borrar_ObjetosLayout = new javax.swing.GroupLayout(Borrar_Objetos.getContentPane());
        Borrar_Objetos.getContentPane().setLayout(Borrar_ObjetosLayout);
        Borrar_ObjetosLayout.setHorizontalGroup(
            Borrar_ObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Borrar_ObjetosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TablaBorrar_Objetos, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
            .addGroup(Borrar_ObjetosLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jb_elTotalObj, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jb_regresarElOvj, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        Borrar_ObjetosLayout.setVerticalGroup(
            Borrar_ObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Borrar_ObjetosLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(TablaBorrar_Objetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addGroup(Borrar_ObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_elTotalObj, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jb_regresarElOvj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_Crear.setText("Crear");
        jb_Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CrearMouseClicked(evt);
            }
        });

        jb_Modificar.setText("Modificar");

        jb_Eliminar.setText("Eliminar");
        jb_Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_EliminarMouseClicked(evt);
            }
        });

        jb_Listar.setText("Listar");
        jb_Listar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ListarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(jb_Crear)
                .addGap(53, 53, 53)
                .addComponent(jb_Modificar)
                .addGap(68, 68, 68)
                .addComponent(jb_Eliminar)
                .addGap(62, 62, 62)
                .addComponent(jb_Listar)
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_Crear)
                    .addComponent(jb_Modificar)
                    .addComponent(jb_Eliminar)
                    .addComponent(jb_Listar))
                .addContainerGap(218, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_NewMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_NewMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_NewMActionPerformed

    private void jb_CrearPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CrearPersonaMouseClicked
        CreacionPersonal.pack();
        CreacionPersonal.setLocationRelativeTo(this);
        CreacionPersonal.setVisible(true);
        Crear.setVisible(false);
    }//GEN-LAST:event_jb_CrearPersonaMouseClicked

    private void jb_CrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CrearMouseClicked
        Crear.pack();
        Crear.setLocationRelativeTo(this);
        Crear.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jb_CrearMouseClicked

    private void jb_crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearMouseClicked
        try {
            String masterPassword = JOptionPane.showInputDialog("Ingrese la contraseña maestra");
            if (masterPassword.equals("unitec1234")) {
                String id = tf_NewId.getText();
                String nombre = tf_newName.getText();
                String e = tf_NewEdad.getText();
                int edad = Integer.parseInt(e);
                String sexo = "";
                if (rb_NewM.isSelected()) {
                    sexo = "M";
                } else if (rb_NewF.isSelected()) {
                    sexo = "F";
                }
                String estado = "";
                if (rb_NewCasado.isSelected()) {
                    estado = "Casado";
                } else if (rb_NewSoltero.isSelected()) {
                    estado = "Soltero";
                }
                String a = tf_NewAltura.getText();
                double altura = Double.parseDouble(a);
                String p = tf_NewAltura.getText();
                double peso = Double.parseDouble(a);

                if (cb_TipoDeUsuario.getSelectedIndex() == 0) {
                    String username = tf_NewUserGerente.getText();
                    String cargo = tf_NewCargoGerente.getText();
                    String password = tf_gerentePassword.getText();
                    Gerente g = new Gerente(username, password, cargo, id, nombre, sexo, estado, altura, peso, edad);
                    personas.add(g);
                    DefaultTableModel tmodelo = (DefaultTableModel) jt_ListaPersonal.getModel();
                    Object[] newrow = {g.getNombre(), cb_TipoDeUsuario.getSelectedItem()};
                    tmodelo.addRow(newrow);
                    jt_ListaPersonal.setModel(tmodelo);

                    DefaultComboBoxModel del = (DefaultComboBoxModel) tablaBorra.getModel();
                    del.addElement(g);
                    tablaBorra.setModel(del);

                    DefaultComboBoxModel u = (DefaultComboBoxModel) cb_personas.getModel();
                    u.addElement(g);
                    cb_personas.setModel(u);

                } else if (cb_TipoDeUsuario.getSelectedIndex() == 1) {
                    String ocupacion = tf_newOcupacionPersonal.getText();
                    String horario = tf_newHorarioPersonal.getText();
                    String t = tf_newTrabajadoPersonal.getText();
                    int tiempo = Integer.parseInt(t);
                    String s = tf_Sueldo.getText();
                    int sueldo = Integer.parseInt(s);
                    Persona_General pg = new Persona_General(ocupacion, horario, tiempo, sueldo, id, nombre, sexo, estado, altura, peso, edad);
                    personas.add(pg);
                    DefaultTableModel tmodelo = (DefaultTableModel) jt_ListaPersonal.getModel();
                    Object[] newrow = {pg.getNombre(), cb_TipoDeUsuario.getSelectedItem()};
                    tmodelo.addRow(newrow);
                    jt_ListaPersonal.setModel(tmodelo);

                    DefaultComboBoxModel del = (DefaultComboBoxModel) tablaBorra.getModel();
                    del.addElement(pg);
                    tablaBorra.setModel(del);

                    DefaultComboBoxModel u = (DefaultComboBoxModel) cb_personas.getModel();
                    u.addElement(pg);
                    cb_personas.setModel(u);

                }
                JOptionPane.showMessageDialog(this, "Se ha creado con exito el nuevo integrante del personal");
                JOptionPane.showMessageDialog(this, "Se ha eliminado de la tabla con exito");
            } else {
                JOptionPane.showMessageDialog(this, "Verifique la contraseña para realizar esta accion");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Valide los datos");
        }


    }//GEN-LAST:event_jb_crearMouseClicked

    private void cb_TipoDeUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_TipoDeUsuarioItemStateChanged
        if (cb_TipoDeUsuario.getSelectedIndex() == 0) {
            tf_NewCargoGerente.setEnabled(true);
            tf_NewUserGerente.setEnabled(true);
            tf_gerentePassword.setEnabled(true);
            tf_newOcupacionPersonal.setEnabled(false);
            tf_newTrabajadoPersonal.setEnabled(false);
            tf_newHorarioPersonal.setEnabled(false);
        } else if (cb_TipoDeUsuario.getSelectedIndex() == 1) {
            tf_NewCargoGerente.setEnabled(false);
            tf_NewUserGerente.setEnabled(false);
            tf_gerentePassword.setEnabled(false);
            tf_newOcupacionPersonal.setEnabled(true);
            tf_newTrabajadoPersonal.setEnabled(true);
            tf_newHorarioPersonal.setEnabled(true);
        }
    }//GEN-LAST:event_cb_TipoDeUsuarioItemStateChanged

    private void jb_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_regresarMouseClicked
        this.pack();
        this.setLocationRelativeTo(this);
        this.setVisible(true);
        CreacionPersonal.setVisible(false);
    }//GEN-LAST:event_jb_regresarMouseClicked

    private void jb_ListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ListarMouseClicked
        Listar.pack();
        Listar.setLocationRelativeTo(this);
        Listar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jb_ListarMouseClicked

    private void jb_listarPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_listarPersonasMouseClicked
        ListarPersonas.pack();
        ListarPersonas.setLocationRelativeTo(this);
        ListarPersonas.setVisible(true);
        Listar.setVisible(false);
    }//GEN-LAST:event_jb_listarPersonasMouseClicked

    private void jb_Regresar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_Regresar2MouseClicked
        this.pack();
        this.setLocationRelativeTo(this);
        this.setVisible(true);
        ListarPersonas.setVisible(false);
    }//GEN-LAST:event_jb_Regresar2MouseClicked

    private void jb_EliminarPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_EliminarPersonaMouseClicked
        try {
            String masterPassword = JOptionPane.showInputDialog("Ingrese la contraseña maestra");

            if (masterPassword.equals("unitec1234")) {
                if (jt_ListaPersonal.getSelectedRow() >= 0) {
                    DefaultTableModel modelo = (DefaultTableModel) jt_ListaPersonal.getModel();
                    modelo.removeRow(jt_ListaPersonal.getSelectedRow());
                    jt_ListaPersonal.setModel(modelo);
                }
                JOptionPane.showMessageDialog(this, "Se ha eliminado de la tabla con exito");
            } else {
                JOptionPane.showMessageDialog(this, "Verifique la contraseña para realizar esta accion");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Valide los datos");
        }
    }//GEN-LAST:event_jb_EliminarPersonaMouseClicked

    private void jb_CrearObjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CrearObjetoMouseClicked
        CrearObjetos.pack();
        CrearObjetos.setLocationRelativeTo(this);
        CrearObjetos.setVisible(true);
        Crear.setVisible(false);
    }//GEN-LAST:event_jb_CrearObjetoMouseClicked

    private void jb_ColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ColorMouseClicked
        jb_Color.setBackground(JColorChooser.showDialog(this, "Elija el color para el contacto", Color.yellow));
    }//GEN-LAST:event_jb_ColorMouseClicked

    private void jb_crearObjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearObjetoMouseClicked
        try {
            String masterPassword = JOptionPane.showInputDialog("Ingrese la contraseña maestra");
            if (masterPassword.equals("unitec1234")) {
                String marca = tf_Newmarca.getText();
                String descripcion = ta_newDescripcion.getText();
                Color color = jb_Color.getBackground();
                String tamaño = tf_NewTamaño.getText();
                String calidad = ta_NewCalidad.getText();
                Persona entrega = (Persona) cb_personas.getSelectedItem();
                if (cb_ListaTiposObjetos.getSelectedIndex() == 0) {

                    String t = tf_talla.getText();
                    int talla = Integer.parseInt(t);
                    
                    String suela = ta_NewSuela.getText();
                    String c = tf_NewComodida.getText();
                    int comodida = Integer.parseInt(c);
                    Zapatos z = new Zapatos(talla, suela, comodida, color, marca, tamaño, calidad, entrega, descripcion);
                    objetos.add(z);
                    DefaultTableModel tmodelo2 = (DefaultTableModel) jt_InventarioObjetos.getModel();
                    Object[] newrow = {z.getMarca(), z.getTamaño(), z.getCalidad(), z.getDescrípcion(), z.getEntrega(), z.getColor()};
                    tmodelo2.addRow(newrow);
                    jt_InventarioObjetos.setModel(tmodelo2);

                } else if (cb_ListaTiposObjetos.getSelectedIndex() == 1) {
                    String talla = "";
                    if (rb_S.isSelected()) {
                        talla = "S";
                    } else if (rb_M.isSelected()) {
                        talla = "M";
                    } else if (rb_L.isSelected()) {
                        talla = "L";
                    }
                    String tela = tf_Newtela.getText();
                    String pais = tf_NewPais.getText();
                    Ropa r = new Ropa(talla, tela, pais, color, marca, tamaño, calidad, entrega, descripcion);
                    objetos.add(r);
                    DefaultTableModel tmodelo2 = (DefaultTableModel) jt_InventarioObjetos.getModel();
                    Object[] newrow = {r.getMarca(), r.getTamaño(), r.getCalidad(), r.getDescrípcion(), r.getEntrega(), r.getColor()};
                    tmodelo2.addRow(newrow);
                    jt_InventarioObjetos.setModel(tmodelo2);

                } else if (cb_ListaTiposObjetos.getSelectedIndex() == 2) {
                    String hogar = ta_newdHogar.getText();
                    String instrucciones = ta_NewInstrucciones.getText();
                    String garantia = tf_newGarantia3.getText();
                    Objetos_Hogar h = new Objetos_Hogar(hogar, instrucciones, garantia, color, marca, tamaño, calidad, entrega, descripcion);
                    objetos.add(h);
                    DefaultTableModel tmodelo2 = (DefaultTableModel) jt_InventarioObjetos.getModel();
                    Object[] newrow = {h.getMarca(), h.getTamaño(), h.getCalidad(), h.getDescrípcion(), h.getEntrega(), h.getColor()};
                    tmodelo2.addRow(newrow);
                    jt_InventarioObjetos.setModel(tmodelo2);

                }
                JOptionPane.showMessageDialog(this, "Se ha añadido un nuevo objeto con exito");
            } else {
                JOptionPane.showMessageDialog(this, "Verifique la contraseña para realizar esta accion");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Valide los datos");
        }

    }//GEN-LAST:event_jb_crearObjetoMouseClicked

    private void cb_ListaTiposObjetosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_ListaTiposObjetosItemStateChanged
        if (cb_ListaTiposObjetos.getSelectedIndex() == 0) {
            tf_talla.setEnabled(true);
            ta_NewSuela.setEnabled(true);
            tf_NewComodida.setEnabled(true);
            rb_L.setEnabled(false);
            rb_M.setEnabled(false);
            rb_S.setEnabled(false);
            tf_Newtela.setEnabled(false);
            tf_NewPais.setEnabled(false);
            ta_newdHogar.setEnabled(false);
            ta_NewInstrucciones.setEnabled(false);
            tf_newGarantia3.setEnabled(false);
        } else if (cb_ListaTiposObjetos.getSelectedIndex() == 1) {
            tf_talla.setEnabled(false);
            ta_NewSuela.setEnabled(false);
            tf_NewComodida.setEnabled(false);
            rb_L.setEnabled(true);
            rb_M.setEnabled(true);
            rb_S.setEnabled(true);
            tf_Newtela.setEnabled(true);
            tf_NewPais.setEnabled(true);
            ta_newdHogar.setEnabled(false);
            ta_NewInstrucciones.setEnabled(false);
            tf_newGarantia3.setEnabled(false);
        } else if (cb_ListaTiposObjetos.getSelectedIndex() == 2) {
            tf_talla.setEnabled(false);
            ta_NewSuela.setEnabled(false);
            tf_NewComodida.setEnabled(false);
            rb_L.setEnabled(false);
            rb_M.setEnabled(false);
            rb_S.setEnabled(false);
            tf_Newtela.setEnabled(false);
            tf_NewPais.setEnabled(false);
            ta_newdHogar.setEnabled(true);
            ta_NewInstrucciones.setEnabled(true);
            tf_newGarantia3.setEnabled(true);
        }
    }//GEN-LAST:event_cb_ListaTiposObjetosItemStateChanged

    private void jb_regresar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_regresar3MouseClicked
        this.pack();
        this.setLocationRelativeTo(this);
        this.setVisible(true);
        CrearObjetos.setVisible(false);
    }//GEN-LAST:event_jb_regresar3MouseClicked

    private void jb_listarObjetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_listarObjetosMouseClicked
        ListarObjetos.pack();
        ListarObjetos.setLocationRelativeTo(this);
        ListarObjetos.setVisible(true);
        Listar.setVisible(false);
    }//GEN-LAST:event_jb_listarObjetosMouseClicked

    private void jb_eliminar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_eliminar2MouseClicked
        try {
            String masterPassword = JOptionPane.showInputDialog("Ingrese la contraseña maestra");

            if (masterPassword.equals("unitec1234")) {
                if (jt_InventarioObjetos.getSelectedRow() >= 0) {
                    DefaultTableModel modelo = (DefaultTableModel) jt_InventarioObjetos.getModel();
                    modelo.removeRow(jt_InventarioObjetos.getSelectedRow());
                    jt_InventarioObjetos.setModel(modelo);
                }
                JOptionPane.showMessageDialog(this, "Se ha eliminado de la tabla con exito");
            } else {
                JOptionPane.showMessageDialog(this, "Verifique la contraseña para realizar esta accion");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Valide los datos");
        }
    }//GEN-LAST:event_jb_eliminar2MouseClicked

    private void jb_regresar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_regresar4MouseClicked
        this.pack();
        this.setLocationRelativeTo(this);
        this.setVisible(true);
        ListarObjetos.setVisible(false);
    }//GEN-LAST:event_jb_regresar4MouseClicked

    private void jb_EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_EliminarMouseClicked
        Eliminar.pack();
        Eliminar.setLocationRelativeTo(this);
        Eliminar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jb_EliminarMouseClicked

    private void jb_ElPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ElPersonaMouseClicked
        Eliminar_Personal.pack();
        Eliminar_Personal.setLocationRelativeTo(this);
        Eliminar_Personal.setVisible(true);
        Eliminar.setVisible(false);
    }//GEN-LAST:event_jb_ElPersonaMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.pack();
        this.setLocationRelativeTo(this);
        this.setVisible(true);
        Eliminar_Personal.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jb_EliminarTotal3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_EliminarTotal3MouseClicked
        try {
            int del = tablaBorra.getSelectedIndex();
            personas.remove(del);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Valide los datos");
        }
    }//GEN-LAST:event_jb_EliminarTotal3MouseClicked

    private void jb_regresarElOvjMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_regresarElOvjMouseClicked
        this.pack();
        this.setLocationRelativeTo(this);
        this.setVisible(true);
        Borrar_Objetos.setVisible(false);
    }//GEN-LAST:event_jb_regresarElOvjMouseClicked

    private void jb_elTotalObjMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_elTotalObjMouseClicked
        try {
            int del = TablaBorrar_Objetos.getSelectedIndex();
            objetos.remove(del);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Valide los datos");
        }
    }//GEN-LAST:event_jb_elTotalObjMouseClicked

    private void jb_ElObjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ElObjetoMouseClicked
        Borrar_Objetos.pack();
        Borrar_Objetos.setLocationRelativeTo(this);
        Borrar_Objetos.setVisible(true);
        Eliminar.setVisible(false);
    }//GEN-LAST:event_jb_ElObjetoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Borrar_Objetos;
    private javax.swing.JDialog CreacionPersonal;
    private javax.swing.JDialog Crear;
    private javax.swing.JDialog CrearObjetos;
    private javax.swing.JDialog Eliminar;
    private javax.swing.JDialog Eliminar_Personal;
    private javax.swing.JDialog Listar;
    private javax.swing.JDialog ListarObjetos;
    private javax.swing.JDialog ListarPersonas;
    private javax.swing.JComboBox<String> TablaBorrar_Objetos;
    private javax.swing.JComboBox<String> cb_ListaTiposObjetos;
    private javax.swing.JComboBox<String> cb_TipoDeUsuario;
    private javax.swing.JComboBox<String> cb_personas;
    private javax.swing.ButtonGroup grputoTallas;
    private javax.swing.ButtonGroup grupoEstadoCivil;
    private javax.swing.ButtonGroup grupoSexo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton jb_Color;
    private javax.swing.JButton jb_Crear;
    private javax.swing.JButton jb_CrearObjeto;
    private javax.swing.JButton jb_CrearPersona;
    private javax.swing.JButton jb_ElObjeto;
    private javax.swing.JButton jb_ElPersona;
    private javax.swing.JButton jb_Eliminar;
    private javax.swing.JButton jb_EliminarPersona;
    private javax.swing.JButton jb_EliminarTotal3;
    private javax.swing.JButton jb_Listar;
    private javax.swing.JButton jb_Modificar;
    private javax.swing.JButton jb_Regresar2;
    private javax.swing.JButton jb_crear;
    private javax.swing.JButton jb_crearObjeto;
    private javax.swing.JButton jb_elTotalObj;
    private javax.swing.JButton jb_eliminar2;
    private javax.swing.JButton jb_listarObjetos;
    private javax.swing.JButton jb_listarPersonas;
    private javax.swing.JButton jb_regresar;
    private javax.swing.JButton jb_regresar3;
    private javax.swing.JButton jb_regresar4;
    private javax.swing.JButton jb_regresarElOvj;
    private javax.swing.JTable jt_InventarioObjetos;
    private javax.swing.JTable jt_ListaPersonal;
    private javax.swing.JRadioButton rb_L;
    private javax.swing.JRadioButton rb_M;
    private javax.swing.JRadioButton rb_NewCasado;
    private javax.swing.JRadioButton rb_NewF;
    private javax.swing.JRadioButton rb_NewM;
    private javax.swing.JRadioButton rb_NewSoltero;
    private javax.swing.JRadioButton rb_S;
    private javax.swing.JTextArea ta_NewCalidad;
    private javax.swing.JTextArea ta_NewInstrucciones;
    private javax.swing.JTextArea ta_NewSuela;
    private javax.swing.JTextArea ta_newDescripcion;
    private javax.swing.JTextArea ta_newdHogar;
    private javax.swing.JComboBox<String> tablaBorra;
    private javax.swing.JTextField tf_NewAltura;
    private javax.swing.JTextField tf_NewCargoGerente;
    private javax.swing.JTextField tf_NewComodida;
    private javax.swing.JTextField tf_NewEdad;
    private javax.swing.JTextField tf_NewId;
    private javax.swing.JTextField tf_NewPais;
    private javax.swing.JTextField tf_NewTamaño;
    private javax.swing.JTextField tf_NewUserGerente;
    private javax.swing.JTextField tf_Newmarca;
    private javax.swing.JTextField tf_Newtela;
    private javax.swing.JTextField tf_Sueldo;
    private javax.swing.JPasswordField tf_gerentePassword;
    private javax.swing.JTextField tf_newGarantia3;
    private javax.swing.JTextField tf_newHorarioPersonal;
    private javax.swing.JTextField tf_newName;
    private javax.swing.JTextField tf_newOcupacionPersonal;
    private javax.swing.JTextField tf_newPeso;
    private javax.swing.JTextField tf_newTrabajadoPersonal;
    private javax.swing.JTextField tf_talla;
    // End of variables declaration//GEN-END:variables

    private ArrayList personas = new ArrayList();

    private ArrayList objetos = new ArrayList();
}
