package examen1p2_andresnuila;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author enuil
 */
public class Pantalla_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla_Principal
     */
    public Pantalla_Principal() {
        initComponents();
        if (cb_TipoDeUsuario.getSelectedIndex() == 0) {
            tf_NewCargoGerente.setEnabled(true);
            tf_NewUserGerente.setEnabled(true);
            tf_gerentePassword.setEnabled(true);
            tf_newOcupacionPersonal.setEnabled(false);
            tf_newTrabajadoPersonal.setEnabled(false);
            tf_newHorarioPersonal.setEnabled(false);
        } else if (cb_TipoDeUsuario.getSelectedIndex() == 1) {
            tf_NewCargoGerente.setEnabled(false);
            tf_NewUserGerente.setEnabled(false);
            tf_gerentePassword.setEnabled(false);
            tf_newOcupacionPersonal.setEnabled(true);
            tf_newTrabajadoPersonal.setEnabled(true);
            tf_newHorarioPersonal.setEnabled(true);
        }
        setLocationRelativeTo(null);
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_TipoDeUsuario.getModel();
        modelo.addElement("Gerente");
        modelo.addElement("Personal General");
        DefaultComboBoxModel modeloO = (DefaultComboBoxModel) cb_ListaTiposObjetos.getModel();
        modeloO.addElement("Zapato");
        modeloO.addElement("Ropa");
        modeloO.addElement("Hogar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Crear = new javax.swing.JDialog();
        jb_CrearPersona = new javax.swing.JButton();
        jb_CrearObjeto = new javax.swing.JButton();
        CreacionPersonal = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cb_TipoDeUsuario = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_NewId = new javax.swing.JTextField();
        tf_newName = new javax.swing.JTextField();
        tf_NewEdad = new javax.swing.JTextField();
        rb_NewM = new javax.swing.JRadioButton();
        rb_NewF = new javax.swing.JRadioButton();
        rb_NewSoltero = new javax.swing.JRadioButton();
        rb_NewCasado = new javax.swing.JRadioButton();
        tf_NewAltura = new javax.swing.JTextField();
        tf_newPeso = new javax.swing.JTextField();
        tf_NewUserGerente = new javax.swing.JTextField();
        tf_NewCargoGerente = new javax.swing.JTextField();
        tf_newOcupacionPersonal = new javax.swing.JTextField();
        tf_newHorarioPersonal = new javax.swing.JTextField();
        tf_newTrabajadoPersonal = new javax.swing.JTextField();
        jb_crear = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        tf_gerentePassword = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        tf_Sueldo = new javax.swing.JTextField();
        jb_regresar = new javax.swing.JButton();
        grupoSexo = new javax.swing.ButtonGroup();
        grupoEstadoCivil = new javax.swing.ButtonGroup();
        Listar = new javax.swing.JDialog();
        jb_listarPersonas = new javax.swing.JButton();
        jb_listarObjetos = new javax.swing.JButton();
        ListarPersonas = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_ListaPersonal = new javax.swing.JTable();
        jb_EliminarPersona = new javax.swing.JButton();
        jb_Regresar2 = new javax.swing.JButton();
        CrearObjetos = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cb_ListaTiposObjetos = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jb_Crear = new javax.swing.JButton();
        jb_Modificar = new javax.swing.JButton();
        jb_Eliminar = new javax.swing.JButton();
        jb_Listar = new javax.swing.JButton();

        jb_CrearPersona.setText("Persona");
        jb_CrearPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CrearPersonaMouseClicked(evt);
            }
        });

        jb_CrearObjeto.setText("Objeto");
        jb_CrearObjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CrearObjetoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CrearLayout = new javax.swing.GroupLayout(Crear.getContentPane());
        Crear.getContentPane().setLayout(CrearLayout);
        CrearLayout.setHorizontalGroup(
            CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jb_CrearPersona)
                .addGap(142, 142, 142)
                .addComponent(jb_CrearObjeto)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        CrearLayout.setVerticalGroup(
            CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addGroup(CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_CrearPersona)
                    .addComponent(jb_CrearObjeto))
                .addContainerGap(242, Short.MAX_VALUE))
        );

        jLabel1.setText("ID");

        jLabel2.setText("Nombre");

        jLabel3.setText("Edad");

        jLabel4.setText("Sexo");

        jLabel5.setText("Estado Civil");

        jLabel6.setText("Altura");

        jLabel7.setText("Peso");

        cb_TipoDeUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_TipoDeUsuarioItemStateChanged(evt);
            }
        });

        jLabel8.setText("Tipo de Usuario");

        jLabel9.setText("Username(Gerente)");

        jLabel10.setText("Cargo(Gerente)");

        jLabel11.setText("Ocupacion(Personal)");

        jLabel12.setText("Horario");

        jLabel13.setText("Tiempo de trabajar (En semanas)");

        tf_NewId.setText("jTextField1");

        tf_newName.setText("jTextField2");

        tf_NewEdad.setText("jTextField3");

        grupoSexo.add(rb_NewM);
        rb_NewM.setText("M");
        rb_NewM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_NewMActionPerformed(evt);
            }
        });

        grupoSexo.add(rb_NewF);
        rb_NewF.setText("F");

        grupoEstadoCivil.add(rb_NewSoltero);
        rb_NewSoltero.setText("Soltero");

        grupoEstadoCivil.add(rb_NewCasado);
        rb_NewCasado.setText("Casado");

        tf_NewAltura.setText("jTextField1");

        tf_newPeso.setText("jTextField1");

        tf_NewUserGerente.setText("jTextField1");

        tf_NewCargoGerente.setText("jTextField1");

        tf_newOcupacionPersonal.setText("jTextField1");

        tf_newHorarioPersonal.setText("jTextField1");

        tf_newTrabajadoPersonal.setText("jTextField1");

        jb_crear.setText("Crear");
        jb_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearMouseClicked(evt);
            }
        });

        jLabel14.setText("Password");

        tf_gerentePassword.setText("jPasswordField1");

        jLabel15.setText("Sueldo");

        tf_Sueldo.setText("jTextField1");

        jb_regresar.setText("REGRESAR");
        jb_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_regresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CreacionPersonalLayout = new javax.swing.GroupLayout(CreacionPersonal.getContentPane());
        CreacionPersonal.getContentPane().setLayout(CreacionPersonalLayout);
        CreacionPersonalLayout.setHorizontalGroup(
            CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreacionPersonalLayout.createSequentialGroup()
                .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreacionPersonalLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jb_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_regresar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreacionPersonalLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CreacionPersonalLayout.createSequentialGroup()
                                .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(40, 40, 40)
                                .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_NewM)
                                    .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_NewId, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                        .addComponent(tf_newName)
                                        .addComponent(tf_NewEdad))))
                            .addGroup(CreacionPersonalLayout.createSequentialGroup()
                                .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(CreacionPersonalLayout.createSequentialGroup()
                                        .addComponent(rb_NewSoltero)
                                        .addGap(18, 18, 18)
                                        .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rb_NewF)
                                            .addComponent(rb_NewCasado)))
                                    .addComponent(tf_NewAltura)
                                    .addComponent(tf_newPeso))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(CreacionPersonalLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_Sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CreacionPersonalLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_newTrabajadoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)
                            .addGroup(CreacionPersonalLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(cb_TipoDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CreacionPersonalLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_newHorarioPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CreacionPersonalLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_newOcupacionPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CreacionPersonalLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_gerentePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_NewUserGerente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreacionPersonalLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_NewCargoGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        CreacionPersonalLayout.setVerticalGroup(
            CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreacionPersonalLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(tf_NewId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_TipoDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreacionPersonalLayout.createSequentialGroup()
                        .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_NewUserGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_NewCargoGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(13, 13, 13))
                    .addGroup(CreacionPersonalLayout.createSequentialGroup()
                        .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_newName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_NewEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreacionPersonalLayout.createSequentialGroup()
                        .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(rb_NewM)
                            .addComponent(rb_NewF)
                            .addComponent(jLabel14))
                        .addGap(22, 22, 22)
                        .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(rb_NewSoltero)
                            .addComponent(rb_NewCasado)
                            .addComponent(jLabel11)
                            .addComponent(tf_newOcupacionPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tf_gerentePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(tf_NewAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12)
                    .addComponent(tf_newHorarioPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_newPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tf_newTrabajadoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_Sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(CreacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreacionPersonalLayout.createSequentialGroup()
                        .addComponent(jb_crear)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreacionPersonalLayout.createSequentialGroup()
                        .addComponent(jb_regresar)
                        .addContainerGap())))
        );

        jb_listarPersonas.setText("Personas");
        jb_listarPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_listarPersonasMouseClicked(evt);
            }
        });

        jb_listarObjetos.setText("Objetos");

        javax.swing.GroupLayout ListarLayout = new javax.swing.GroupLayout(Listar.getContentPane());
        Listar.getContentPane().setLayout(ListarLayout);
        ListarLayout.setHorizontalGroup(
            ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jb_listarPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(jb_listarObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        ListarLayout.setVerticalGroup(
            ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_listarObjetos, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(jb_listarPersonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(243, Short.MAX_VALUE))
        );

        jt_ListaPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Rol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_ListaPersonal);

        jb_EliminarPersona.setText("Eliminar");
        jb_EliminarPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_EliminarPersonaMouseClicked(evt);
            }
        });

        jb_Regresar2.setText("Regresar");
        jb_Regresar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_Regresar2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ListarPersonasLayout = new javax.swing.GroupLayout(ListarPersonas.getContentPane());
        ListarPersonas.getContentPane().setLayout(ListarPersonasLayout);
        ListarPersonasLayout.setHorizontalGroup(
            ListarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarPersonasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addGroup(ListarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_EliminarPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_Regresar2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        ListarPersonasLayout.setVerticalGroup(
            ListarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarPersonasLayout.createSequentialGroup()
                .addGroup(ListarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListarPersonasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ListarPersonasLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jb_EliminarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(jb_Regresar2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel16.setText("Color");

        jLabel17.setText("Marca");

        jLabel18.setText("Descripcion");

        jLabel19.setText("Tamaño");

        jLabel20.setText("Calidad");

        jLabel21.setText("Que persona lo ingreso al sistema");

        jLabel22.setText("Tipo de objeto");

        jLabel23.setText("Talla");

        jLabel24.setText("Descripcion Suela");

        jLabel25.setText("Escala de comodidad");

        jLabel26.setText("Talla");

        jLabel27.setText("Tipo de Tela");

        jLabel28.setText("Pais de elaboracion");

        jLabel29.setText("Descripcion");

        jLabel31.setText("Instruciones");

        jLabel32.setText("Tiempo de garantia en meses");

        javax.swing.GroupLayout CrearObjetosLayout = new javax.swing.GroupLayout(CrearObjetos.getContentPane());
        CrearObjetos.getContentPane().setLayout(CrearObjetosLayout);
        CrearObjetosLayout.setHorizontalGroup(
            CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearObjetosLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(CrearObjetosLayout.createSequentialGroup()
                        .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(218, 218, 218)
                        .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25)
                            .addComponent(jLabel23)
                            .addGroup(CrearObjetosLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(52, 52, 52)
                                .addComponent(cb_ListaTiposObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel24)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addGroup(CrearObjetosLayout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel30))
                            .addComponent(jLabel32))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        CrearObjetosLayout.setVerticalGroup(
            CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearObjetosLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel22)
                    .addComponent(cb_ListaTiposObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addGap(14, 14, 14)
                .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addGroup(CrearObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(110, 110, 110))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_Crear.setText("Crear");
        jb_Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CrearMouseClicked(evt);
            }
        });

        jb_Modificar.setText("Modificar");

        jb_Eliminar.setText("Eliminar");

        jb_Listar.setText("Listar");
        jb_Listar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ListarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(jb_Crear)
                .addGap(53, 53, 53)
                .addComponent(jb_Modificar)
                .addGap(68, 68, 68)
                .addComponent(jb_Eliminar)
                .addGap(62, 62, 62)
                .addComponent(jb_Listar)
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_Crear)
                    .addComponent(jb_Modificar)
                    .addComponent(jb_Eliminar)
                    .addComponent(jb_Listar))
                .addContainerGap(218, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_NewMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_NewMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_NewMActionPerformed

    private void jb_CrearPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CrearPersonaMouseClicked
        CreacionPersonal.pack();
        CreacionPersonal.setLocationRelativeTo(this);
        CreacionPersonal.setVisible(true);
        Crear.setVisible(false);
    }//GEN-LAST:event_jb_CrearPersonaMouseClicked

    private void jb_CrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CrearMouseClicked
        Crear.pack();
        Crear.setLocationRelativeTo(this);
        Crear.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jb_CrearMouseClicked

    private void jb_crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearMouseClicked
        try {
            String id = tf_NewId.getText();
            String nombre = tf_newName.getText();
            String e = tf_NewEdad.getText();
            int edad = Integer.parseInt(e);
            String sexo = "";
            if (rb_NewM.isSelected()) {
                sexo = "M";
            } else if (rb_NewF.isSelected()) {
                sexo = "F";
            }
            String estado = "";
            if (rb_NewCasado.isSelected()) {
                estado = "Casado";
            } else if (rb_NewSoltero.isSelected()) {
                estado = "Soltero";
            }
            String a = tf_NewAltura.getText();
            double altura = Double.parseDouble(a);
            String p = tf_NewAltura.getText();
            double peso = Double.parseDouble(a);

            if (cb_TipoDeUsuario.getSelectedIndex() == 0) {
                String username = tf_NewUserGerente.getText();
                String cargo = tf_NewCargoGerente.getText();
                String password = tf_gerentePassword.getText();
                Gerente g = new Gerente(username, password, cargo, id, nombre, sexo, estado, altura, peso, edad);
                DefaultTableModel tmodelo = (DefaultTableModel) jt_ListaPersonal.getModel();
                Object[] newrow = {g.getNombre(), cb_TipoDeUsuario.getSelectedItem()};
                tmodelo.addRow(newrow);
                jt_ListaPersonal.setModel(tmodelo);
            } else if (cb_TipoDeUsuario.getSelectedIndex() == 1) {
                String ocupacion = tf_newOcupacionPersonal.getText();
                String horario = tf_newHorarioPersonal.getText();
                String t = tf_newTrabajadoPersonal.getText();
                int tiempo = Integer.parseInt(t);
                String s = tf_Sueldo.getText();
                int sueldo = Integer.parseInt(s);
                Persona_General pg = new Persona_General(ocupacion, horario, tiempo, sueldo, id, nombre, sexo, estado, altura, peso, edad);
                DefaultTableModel tmodelo = (DefaultTableModel) jt_ListaPersonal.getModel();
                Object[] newrow = {pg.getNombre(), cb_TipoDeUsuario.getSelectedItem()};
                tmodelo.addRow(newrow);
                jt_ListaPersonal.setModel(tmodelo);
            }
            JOptionPane.showMessageDialog(this, "Se ha creado con exito el nuevo integrante del personal");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Valide los datos");
        }


    }//GEN-LAST:event_jb_crearMouseClicked

    private void cb_TipoDeUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_TipoDeUsuarioItemStateChanged
        if (cb_TipoDeUsuario.getSelectedIndex() == 0) {
            tf_NewCargoGerente.setEnabled(true);
            tf_NewUserGerente.setEnabled(true);
            tf_gerentePassword.setEnabled(true);
            tf_newOcupacionPersonal.setEnabled(false);
            tf_newTrabajadoPersonal.setEnabled(false);
            tf_newHorarioPersonal.setEnabled(false);
        } else if (cb_TipoDeUsuario.getSelectedIndex() == 1) {
            tf_NewCargoGerente.setEnabled(false);
            tf_NewUserGerente.setEnabled(false);
            tf_gerentePassword.setEnabled(false);
            tf_newOcupacionPersonal.setEnabled(true);
            tf_newTrabajadoPersonal.setEnabled(true);
            tf_newHorarioPersonal.setEnabled(true);
        }
    }//GEN-LAST:event_cb_TipoDeUsuarioItemStateChanged

    private void jb_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_regresarMouseClicked
        this.pack();
        this.setLocationRelativeTo(this);
        this.setVisible(true);
        CreacionPersonal.setVisible(false);
    }//GEN-LAST:event_jb_regresarMouseClicked

    private void jb_ListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ListarMouseClicked
        Listar.pack();
        Listar.setLocationRelativeTo(this);
        Listar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jb_ListarMouseClicked

    private void jb_listarPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_listarPersonasMouseClicked
        ListarPersonas.pack();
        ListarPersonas.setLocationRelativeTo(this);
        ListarPersonas.setVisible(true);
        Listar.setVisible(false);
    }//GEN-LAST:event_jb_listarPersonasMouseClicked

    private void jb_Regresar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_Regresar2MouseClicked
        this.pack();
        this.setLocationRelativeTo(this);
        this.setVisible(true);
        ListarPersonas.setVisible(false);
    }//GEN-LAST:event_jb_Regresar2MouseClicked

    private void jb_EliminarPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_EliminarPersonaMouseClicked
        String masterPassword = JOptionPane.showInputDialog("Ingrese la contraseña maestra");
        if (masterPassword.equals("unitec1234")) {
            if (jt_ListaPersonal.getSelectedRow() >= 0) {
                DefaultTableModel modelo = (DefaultTableModel) jt_ListaPersonal.getModel();
                modelo.removeRow(jt_ListaPersonal.getSelectedRow());
                jt_ListaPersonal.setModel(modelo);
            }
            JOptionPane.showMessageDialog(this, "Se ha eliminado de la tabla con exito");
        } else {
            JOptionPane.showMessageDialog(this, "Verifique la contraseña para realizar esta accion");
        }
    }//GEN-LAST:event_jb_EliminarPersonaMouseClicked

    private void jb_CrearObjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CrearObjetoMouseClicked
        CrearObjetos.pack();
        CrearObjetos.setLocationRelativeTo(this);
        CrearObjetos.setVisible(true);
        Crear.setVisible(false);
    }//GEN-LAST:event_jb_CrearObjetoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog CreacionPersonal;
    private javax.swing.JDialog Crear;
    private javax.swing.JDialog CrearObjetos;
    private javax.swing.JDialog Listar;
    private javax.swing.JDialog ListarPersonas;
    private javax.swing.JComboBox<String> cb_ListaTiposObjetos;
    private javax.swing.JComboBox<String> cb_TipoDeUsuario;
    private javax.swing.ButtonGroup grupoEstadoCivil;
    private javax.swing.ButtonGroup grupoSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_Crear;
    private javax.swing.JButton jb_CrearObjeto;
    private javax.swing.JButton jb_CrearPersona;
    private javax.swing.JButton jb_Eliminar;
    private javax.swing.JButton jb_EliminarPersona;
    private javax.swing.JButton jb_Listar;
    private javax.swing.JButton jb_Modificar;
    private javax.swing.JButton jb_Regresar2;
    private javax.swing.JButton jb_crear;
    private javax.swing.JButton jb_listarObjetos;
    private javax.swing.JButton jb_listarPersonas;
    private javax.swing.JButton jb_regresar;
    private javax.swing.JTable jt_ListaPersonal;
    private javax.swing.JRadioButton rb_NewCasado;
    private javax.swing.JRadioButton rb_NewF;
    private javax.swing.JRadioButton rb_NewM;
    private javax.swing.JRadioButton rb_NewSoltero;
    private javax.swing.JTextField tf_NewAltura;
    private javax.swing.JTextField tf_NewCargoGerente;
    private javax.swing.JTextField tf_NewEdad;
    private javax.swing.JTextField tf_NewId;
    private javax.swing.JTextField tf_NewUserGerente;
    private javax.swing.JTextField tf_Sueldo;
    private javax.swing.JPasswordField tf_gerentePassword;
    private javax.swing.JTextField tf_newHorarioPersonal;
    private javax.swing.JTextField tf_newName;
    private javax.swing.JTextField tf_newOcupacionPersonal;
    private javax.swing.JTextField tf_newPeso;
    private javax.swing.JTextField tf_newTrabajadoPersonal;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Gerente> gerentes = new ArrayList();
    private ArrayList<Persona_General> personal = new ArrayList();
}
